### ISSUE TITLE
Cannot find r2ghidra-dec

### ISSUE THREAD

**Issue by hitfzyangdianshi** [radareorg/radare2-pm#116]
After installing https://github.com/radareorg/radare2  , I use command 

`RUN r2pm init && r2pm -i r2ghidra-dec`

and the error message is: `Cannot find r2ghidra-dec`

I tried `r2pm update` , but it does not work. 

I am using the docker (https://github.com/pwncollege/pwncollege/issues/5#issue-814069125 ) when I met this issue. and I tried the command on Ubuntu, and the issue still exists.

**Comment by trufae** [comment]
The package is now named r2ghidra
