### ISSUE TITLE
Update iaito installation script

### ISSUE THREAD

**Issue by stellarix** [radareorg/radare2-pm#130]
Radare2 installed from git
Iaito installed using r2pm -i iaito

```
[ arch ~ ]$ iaito
iaito: error while loading shared libraries: libr_core.so: cannot open shared object file: No such file or directory

```
I had to add `/usr/local/lib` to `/etc/ld.so.conf` in order to make iaito running. https://github.com/radareorg/iaito/issues/59

**Comment by trufae** [comment]
can you try again?

**Comment by stellarix** [comment]
Yes, it worked now.
