### ISSUE TITLE
Bug: Nothing to upgrade, but actually does upgrade...

### ISSUE THREAD

**Issue by cryptax** [radareorg/radare2-pm#164]
I was trying to install decai, but r2pm couldn't find it in the list of available packages.

```
$ r2pm -s | grep decai
$
```

So, I updated. It replies "Nothing to upgrade" but I believe this is misleading: made me believe nothing happened.

```
$ r2pm -U
INFO: Nothing to upgrade
```

After that, I search again for decai, and I find it. So, `-U` did do something. The info message is misleading.

```
$ r2pm -s | grep decai
decai               r2ai/OpenAI/Anthropic/ollama based decompiler, formerly known as r2ai-decai
```

This is my r2pm version:

```
$ r2pm -v
r2pm 5.9.5 32512 @ linux-x86-64
birth: git.5.9.4-18-ge382b998a7 2024-08-19__16:56:23
commit: e382b998a70dfc667f3cdd3e73fbee4ae51c9dbb
options: gpl -O? cs:5 cl:2 make
```

**Comment by trufae** [comment]
That's just a missing verbosity thing. fixed in r2 master now and updated manpage
