### ISSUE TITLE
r2pm support for Cygwin and MinGW

### ISSUE THREAD

**Issue by crowell** [radareorg/radare2-pm#5]
_From @XVilka on December 22, 2015 16:2_

To install it along with other binaries and ability to use it also.

_Copied from original issue: radare/radare2#3869_

**Comment by crowell** [comment]
_From @radare on December 22, 2015 18:14_

U mean w32dist? Because it should work already

**Comment by XVilka** [comment]
I'll check it today at windows machine.

**Comment by XVilka** [comment]
@radare can we close this? Since we removed their support anyway.

**Comment by radare** [comment]
yes, kill it
