### ISSUE TITLE
Add dependency checks to r2pm

### ISSUE THREAD

**Issue by crowell** [radareorg/radare2-pm#6]
_From @zlowram on June 1, 2016 20:21_

Make r2pm install fail if there are unmet dependencies

_Copied from original issue: radare/radare2#5062_

**Comment by crowell** [comment]
@zlowram just to be sure you mean things like checking that unicorn-lib is installed for unicorn, and not that thigns like glib-dev is installed for unicorn-lib. (the former sounds reasonable, the latter, out of scope imo).

**Comment by crowell** [comment]
_From @zlowram on June 1, 2016 20:31_

Yup, exactly. And that when installing radeco rust is installed, etc.

**Comment by XVilka** [comment]
Will be done in a new r2pm https://github.com/radareorg/r2pm/issues/1
