### ISSUE TITLE
Support binary packages

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2-pm#61]
We need a binary r2pm tool that will fetch binary builds of the packages. The reason for this is because Windows, Android and iOS users usually don't have a compiler and r2pm is a shellscript that may not work on those platforms without dependencies or other tools installed.

We can put all those builds in branches or in another repo, but we need a way to automate the build of most interesting plugins like keystone, dirtycow, ... for those platforms

**Comment by XVilka** [comment]
Will be done with a new r2pm - https://github.com/radareorg/r2pm/issues/7
