### ISSUE TITLE
r2golf install error

### ISSUE THREAD

**Issue by sodomak** [radareorg/radare2-pm#91]
I have the issue with installing r2golf plugin.
r2pm version 3.9.0
Arch and Kali - both the same.

> root@kali:~/temp/radare2-3.9.0# r2pm -i r2golf
> Already up to date.
> Install Done For r2golf
> cc -g -I/usr/include/libr -lr_core -lssl -lcrypto -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_parse -lr_flag -lr_cons -lr_reg -lr_search -lr_syscall -lr_fs -lr_io -lr_socket -lr_magic -lr_crypto -lr_hash -lr_util -ldl -shared -o r2golf.so plugin.c
> /usr/bin/ld: /tmp/ccEFKDx0.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:7: all] Error 1
> mkdir -p "/root/.local/share/radare2/plugins"
> cp -f r2golf.so "/root/.local/share/radare2/plugins"
> cp: cannot stat 'r2golf.so': No such file or directory
> make: *** [Makefile:11: install] Error 1
>

**Comment by radare** [comment]
Should be fixed now please confirm

**Comment by sodomak** [comment]
Works on Arch Linux with no issue now, thank you. Good job.
I'll check on Kali later today.

**Comment by sodomak** [comment]
Kali works as well, thanks!
