### ISSUE TITLE
r2pm -d / --doc not working

### ISSUE THREAD

**Issue by rgnkn** [radareorg/radare2-pm#99]
The -d / --doc switch doesn't seem to work. I use "?*" within r2 to gain quick information on changes by diffing and I'd like to have something similar for plugins. "?*" doesn't add plugin commands documentation for this.

If I type in any "r2pm -d" request the terminal only responds with the according help entry, e.g.:

$ r2pm -d pyc
> Usage: r2pm -d [package]  # show docs on [package]

I'd expect any kind of documentation.

I just used:

$ r2pm -v
> r2pm 4.5.0-git

with:

$ r2 -v
> radare2 4.5.0-git 24563 @ linux-x86-64 git.4.4.0-88-g2bf97bf57
> commit: 2bf97bf5703cb8768871c72cd2bcd7009a9726ed build: 2020-04-27__09:28:08

... but this problem remains since I first tried it.

n.b.: I will post an enhancement request for radare2 in a minute, as I'd prefer to get the centrally through r2 via "?*". In case you'd implement that enhancement I wouldn't mind r2pm -d working or not.

**Comment by trufae** [comment]
works fine in latest r2, didnt check before sorry-- so it works with the shellscript and C implementtions as expected

```
$ r2pm -d r2frida

r2frida is an IO plugin for r2 that talks with Frida.
This allows to interact with local and remote processes.

$ r2 frida:///bin/ls
[0x00000000]> :i*
e asm.arch=x86
e asm.bits=64
e asm.os=darwin

You can also connect to Android/iOS gadgets or servers:

$ r2 frida://{device-id}/{application-name|process-id}

$ R2PM_NATIVE=1 r2pm -d r2frida
r2frida is an IO plugin for r2 that talks with Frida.
This allows to interact with local and remote processes.

$ r2 frida:///bin/ls
[0x00000000]> :i*
e asm.arch=x86
e asm.bits=64
e asm.os=darwin

You can also connect to Android/iOS gadgets or servers:

$ r2 frida://{device-id}/{application-name|process-id}
$
```
